config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title='authorization-service-by-phone-number',
        default_version='v1',
        description='Your API description',
        terms_of_service='https://www.yourapp.com/terms/',
        contact=openapi.Contact(email='contact@yourapp.com'),
        license=openapi.License(name='Your License'),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('login_ui.urls', namespace='login_ui')),

    path('users/', include('users.urls', namespace='users')),

    path('doc/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
         name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_ui/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from login_ui.apps import LoginUiConfig
from login_ui.views import IndexView, ProfileView, VerifyView

app_name = LoginUiConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('verify/', VerifyView.as_view(), name='verify'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import (LoginAPIView, ProfileRetrieveAPIView,
                         ProfileUpdateAPIView, RefreshTokenAPIView,
                         VerifyAPIView)

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginAPIView.as_view(), name='login'),
    path('verify/', VerifyAPIView.as_view(), name='verify'),
    path('refresh/', RefreshTokenAPIView.as_view(), name='refresh'),
    path('retrieve/<str:phone>/',
         ProfileRetrieveAPIView.as_view(), name='retrieve'),
    path('update/<str:phone>/', ProfileUpdateAPIView.as_view(), name='update'),
]

login_ui/models.py
from django.db import models

# Create your models here.

login_ui/views.py
from typing import Any

import requests
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import TemplateView
from rest_framework import status

from login_ui.utils.profile_view import (add_user_data_to_context,
                                         get_current_data_about_user,
                                         post_new_user_data)
from login_ui.utils.verify_view import send_post_user_data
from users.models import User


# Create your views here.


class IndexView(TemplateView):
    """Главная страница с вводом номера телефона."""
    template_name = 'login_ui/index.html'
    url = 'http://127.0.0.1:8000/users/login/'

    def post(self, request):
        """
        Получить телефон пользователя из пост запроса от фронтенда.
        Отправить телефон на эндпоинт апи, где на номер телефона(почту)
        отправляется сгенерированный пароль.
        """
        phone = request.POST.get('phone')
        response = requests.post(self.url, data={'phone': phone})
        response = response.json()
        request.session['phone'] = phone

        # Для тестового вывода пароля
        request.session['otp'] = response.get('message').split('$')[1]

        return redirect('login_ui:verify')


class VerifyView(TemplateView):
    """
    Подтверждение номера телефона с помощью случайного пароля,
    отправленного на почту(телефон).
    """
    template_name = 'login_ui/verify.html'
    url = 'http://127.0.0.1:8000/users/verify/'

    def get_context_data(self, **kwargs):
        """
        Добавить в контекст телефон из сессии что бы он отображался
        в строке ввода телефона по дефолту.
        """
        context = super().get_context_data(**kwargs)
        phone = self.request.session.get('phone')
        context['phone'] = phone

        # Для тестового вывода пароля
        context['otp'] = self.request.session.get('otp')

        return context

    def post(self, request):
        """
         Аутентифицировать пользователя по номеру и паролю.
         Получить токены доступа и обновления.
         Залогинить пользователя.
        """
        phone = request.POST.get('phone').replace(' ', '').replace('+', '')
        password = request.POST.get('password')

        response = send_post_user_data(self, phone, password)

        if response.status_code == status.HTTP_200_OK:
            response = response.json()

            access_token = response.get('access_token')
            refresh_token = response.get('refresh_token')

            request.session['access_token'] = access_token
            request.session['refresh_token'] = refresh_token

            user = User.objects.get(phone=phone)
            login(request, user)

        return redirect('login_ui:index')


class ProfileView(TemplateView):
    """Просмотр и обновление профиля пользователя."""

    template_name = 'login_ui/profile.html'
    url = 'http://127.0.0.1:8000/users'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """Отправить текущую информацию о профиле пользователя в шаблон."""
        context = super().get_context_data(**kwargs)

        access_token = self.request.session.get('access_token')
        response = get_current_data_about_user(self, access_token)

        if response.status_code == status.HTTP_200_OK:
            add_user_data_to_context(context, response)

        return context

    def post(self, request):
        """Обновить информацию о профиле пользователя."""
        post_new_user_data(self, request)

        return redirect('login_ui:profile')

login_ui/templates/login_ui/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href={% static 'bootstrap/css/bootstrap.min.css' %}>
    <link rel="stylesheet" href={% static 'styles/nav-bar.css' %}>
    <link rel="stylesheet" href={% static 'styles/global.css' %}>
    <link rel="stylesheet" href={% static 'styles/index.css' %}>
    <link rel="stylesheet" href={% static 'styles/contacts.css' %}>
    <link rel="stylesheet" href={% static 'styles/product_detail.css' %}>
    <link rel="stylesheet" href={% static 'styles/blogentry_list.css' %}>
    <link rel="stylesheet" href={% static 'styles/blogentry_form.css' %}>
    <link rel="stylesheet" href={% static 'styles/login.css' %}>
    <link rel="stylesheet" href={% static 'styles/category.css' %}>
    <title>Document</title>
</head>
<body>


<header>
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href={% url 'login_ui:index' %}>LOGO</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Переключатель навигации">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {{ is_active_main }}" aria-current="page" href={% url 'login_ui:index' %}>Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ is_active_categories }}" aria-current="page" href="#">#</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ is_active_blog }}" href="#">#</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ is_active_contact }}" href="#">#</a>
                    </li>
                </ul>

                <ul class="navbar-nav login">

                    {% if user.is_authenticated %}
                        
                        <li class="nav-item">
                            <a class="nav-link {{ is_active_profile }}" aria-current="page" href={% url 'login_ui:profile' %}>Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href={% url 'login_ui:logout' %}>Выход</a>
                        </li>

                    {% else %}

                        <li class="nav-item">
                            <a class="nav-link {{ is_active_enter }}" aria-current="page" href="#">Вход</a>
                        </li> 

                    {% endif %}
             
                </ul>

            </div>
        </div>
    </nav>
</header>


<section>
    <div class="container-fluid section">
        {% block content %}
        
    

        {% endblock %}    
    </div>
</section>


<footer>

</footer>


<script src="/static/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

login_ui/templates/login_ui/index.html
{% extends 'login_ui/base.html' %}

{% block content %}
{% if not user.is_authenticated %}
  <div>
    <div>
        <h1 style="color: aliceblue; text-align: center;">Вход по номеру телефона</h1>
    </div>
    <form method="post">
        {% csrf_token %}
      <div class="card" style="width: 30%; margin-inline: auto;">
        <div class="card-body">
          <div class="mb-3">
            <input class="form-control" type="tel" id="phone" name="phone" pattern="\+[0-9]{1,3} [0-9]{3} [0-9]{3} [0-9]{2} [0-9]{2}" required>
            <small>Пример: +7 900 900 80 80</small>
            <div id="emailHelp" class="form-text">Введите ваш номер телефона</div>
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
      </div>
    </form>
  </div>
{% else %}
<div>
  <h1 style="color: aliceblue; text-align: center;">Вы авторизованы</h1>
</div>
{% endif %}
{% endblock %}

login_ui/templates/login_ui/profile.html
{% extends 'login_ui/base.html' %}

{% block content %}
  <div>
    <div>
      <h1 style="color: aliceblue; text-align: center;">Данные профиля</h1>
    </div>
    <form method="post">
      {% csrf_token %}
      <div class="card" style="width: 30%; margin-inline: auto;">
        <div class="card-body">
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Телефон</label>
            <p>{{ phone }}</p>
            <hr />
            <label for="exampleInputEmail1" class="form-label">Email</label>
            <input class="form-control mb-3" type="email" name="email" value="{{ email }}" />

            <label for="exampleInputEmail1" class="form-label">Имя</label>
            <input class="form-control mb-3" type="text" name="first_name" value="{{ first_name }}" />

            <label for="exampleInputEmail1" class="form-label">Фамилия</label>
            <input class="form-control mb-3" type="text" name="last_name" value="{{ last_name }}" />

            {% if someone_invite_code %}
              <hr />
              <label for="exampleInputEmail1" class="form-label">Код, пригласившего вас пользователя.</label>
              <p style="font-weight: 700; font-style: italic;">{{ someone_invite_code }}</p>
            {% else %}
              <label for="exampleInputEmail1" class="form-label">Код, пригласившего вас пользователя</label>
              <input class="form-control mb-3" type="text" name="someone_invite_code" />
            {% endif %}

            <hr />
            <label for="exampleInputEmail1" class="form-label">Ваш код приглашения</label>
            <p style="font-weight: 700; font-style: italic;">{{ personal_invitation_code }}</p>
            <hr />

            <label for="exampleInputEmail1" class="form-label">Те, кого пригласили вы</label>
            <ul class="list-group list-group-flush">
              {% for user in invited_users %}
                <li class="list-group-item">{{ user.phone }}</li>
              {% endfor %}
            </ul>
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

login_ui/templates/login_ui/verify.html
{% extends 'login_ui/base.html' %}

{% block content %}
  <div>
    <div>
        <h1 style="color: aliceblue; text-align: center;">Подтвердие вход</h1>
        <p style="color: aliceblue; text-align: center;">На вашу поту отправлен пароль для входа</p>
    </div>
    <form method="post">
        {% csrf_token %}
      <div class="card" style="width: 30%; margin-inline: auto;">
        <div class="card-body">
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Номер телефона</label>
            <input class="form-control mb-3" type="tel" id="phone" name="phone" pattern="\+[0-9]{1,3} [0-9]{3} [0-9]{3} [0-9]{2} [0-9]{2}" required value="{{ phone }}">
            <label for="exampleInputEmail1" class="form-label">Пароль</label>
            <input class="form-control" placeholder="Введите четырехзначный пароль" name="password">
          </div>
          <p>Для теста, пароль выводится сюда: {{ otp }}</p>
          <p>После входа пароль сбрасывается, он одноразовый.</p>
          <button type="submit" class="btn btn-primary">Войти</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}